### ISSUE TITLE
yarn 出错

### ISSUE THREAD

**Issue by mawei1191546352** [aiyuekuang/react_home#13]
warning "antd > react-slick@0.15.4" has incorrect peer dependency "react@^0.14.0 || ^15.0.1".
warning "antd > react-slick@0.15.4" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.1".
warning "antd > react-slick > slick-carousel@1.8.1" has unmet peer dependency "jquery@>=1.8.0".
warning " > react-apollo@2.1.4" has unmet peer dependency "apollo-client@^2.2.3".

然后项目
yarn run start 
项目报错

ERROR in ./node_modules/antd/es/alert/style/index.less
Module build failed: ModuleBuildError: Module build failed:

/* stylelint-disable declaration-bang-space-before */
^
Cannot read property 'length' of undefined
      in C:\Users\JackMa\Desktop\demo\react_home\node_modules\antd\es\style\color\bezierEasing.less (line 1, column -1)
    at runLoaders (C:\Users\JackMa\Desktop\demo\react_home\node_modules\webpack\lib\NormalModule.js:252:20)
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at <anonymous>
 @ ./node_modules/antd/es/alert/style/index.js 2:0-22
 @ ./src/components/zhuye/index.js
 @ ./src/routes.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3012 webpack/hot/dev-server babel-polyfill ./src/index.js

ERROR in ./node_modules/antd/es/style/index.less
Module build failed: ModuleBuildError: Module build failed:

/* stylelint-disable declaration-bang-space-before */
^
Cannot read property 'length' of undefined
      in C:\Users\JackMa\Desktop\demo\react_home\node_modules\antd\es\style\color\bezierEasing.less (line 1, column -1)
    at runLoaders (C:\Users\JackMa\Desktop\demo\react_home\node_modules\webpack\lib\NormalModule.js:252:20)
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at <anonymous>
 @ ./node_modules/antd/es/input/style/index.js 1:0-32
 @ ./src/components/zhuye/index.js
 @ ./src/routes.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3012 webpack/hot/dev-server babel-polyfill ./src/index.js

ERROR in ./node_modules/antd/es/input/style/index.less
Module build failed: ModuleBuildError: Module build failed:

/* stylelint-disable declaration-bang-space-before */
^
Cannot read property 'length' of undefined
      in C:\Users\JackMa\Desktop\demo\react_home\node_modules\antd\es\style\color\bezierEasing.less (line 1, column -1)
    at runLoaders (C:\Users\JackMa\Desktop\demo\react_home\node_modules\webpack\lib\NormalModule.js:252:20)
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at <anonymous>
 @ ./node_modules/antd/es/input/style/index.js 2:0-22
 @ ./src/components/zhuye/index.js
 @ ./src/routes.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3012 webpack/hot/dev-server babel-polyfill ./src/index.js

ERROR in ./node_modules/antd/es/notification/style/index.less
Module build failed: ModuleBuildError: Module build failed:

/* stylelint-disable declaration-bang-space-before */
^
Cannot read property 'length' of undefined
      in C:\Users\JackMa\Desktop\demo\react_home\node_modules\antd\es\style\color\bezierEasing.less (line 1, column -1)
    at runLoaders (C:\Users\JackMa\Desktop\demo\react_home\node_modules\webpack\lib\NormalModule.js:252:20)
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at <anonymous>
 @ ./node_modules/antd/es/notification/style/index.js 2:0-22
 @ ./src/actions/index.js
 @ ./src/components/zhuye/index.js
 @ ./src/routes.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3012 webpack/hot/dev-server babel-polyfill ./src/index.js

ERROR in ./src/style/ztao.scss
Module build failed: ModuleBuildError: Module build failed: Error: Missing binding C:\Users\JackMa\Desktop\demo\react_home\node_modules\node-sass\vendor\win32-x64-57\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (C:\Users\JackMa\Desktop\demo\react_home\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\Users\JackMa\Desktop\demo\react_home\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\JackMa\Desktop\demo\react_home\node_modules\sass-loader\lib\loader.js:3:14)
    at runLoaders (C:\Users\JackMa\Desktop\demo\react_home\node_modules\webpack\lib\NormalModule.js:252:20)
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\JackMa\Desktop\demo\react_home\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
 @ ./src/index.js 21:0-28
 @ multi (webpack)-dev-server/client?http://localhost:3012 webpack/hot/dev-server babel-polyfill ./src/index.js
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/sass-loader/lib/loader.js!src/style/ztao.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js??ref--5-1!./node_modules/sass-loader/lib/loader.js!./src/style/ztao.scss] ./node_modules/css-loader??ref--5-1!./node_modules/sass-loader/lib/loader.js!./src/style/ztao.scss 1.18 KiB {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./src/style/ztao.scss (./node_modules/css-loader??ref--5-1!./node_modules/sass-loader/lib/loader.js!./src/style/ztao.scss)
    Module build failed: Error: Missing binding C:\Users\JackMa\Desktop\demo\react_home\node_modules\node-sass\vendor\win32-x64-57\binding.node
    Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x

    Found bindings for the following environments:
      - Windows 64-bit with Node.js 8.x

    This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass --force` to build the binding for your current environment.
        at module.exports (C:\Users\JackMa\Desktop\demo\react_home\node_modules\node-sass\lib\binding.js:15:13)
        at Object.<anonymous> (C:\Users\JackMa\Desktop\demo\react_home\node_modules\node-sass\lib\index.js:14:35)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\Users\JackMa\Desktop\demo\react_home\node_modules\sass-loader\lib\loader.js:3:14)
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--6-1!node_modules/less-loader/dist/cjs.js??ref--6-2!node_modules/antd/es/alert/style/index.less:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/alert/style/index.less] ./node_modules/css-loader??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/alert/style/index.less 287 bytes {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./node_modules/antd/es/alert/style/index.less (./node_modules/css-loader??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/alert/style/index.less)
    Module build failed:

    /* stylelint-disable declaration-bang-space-before */
    ^
    Cannot read property 'length' of undefined
          in C:\Users\JackMa\Desktop\demo\react_home\node_modules\antd\es\style\color\bezierEasing.less (line 1, column -1)
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--6-1!node_modules/less-loader/dist/cjs.js??ref--6-2!node_modules/antd/es/input/style/index.less:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/input/style/index.less] ./node_modules/css-loader??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/input/style/index.less 287 bytes {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./node_modules/antd/es/input/style/index.less (./node_modules/css-loader??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/input/style/index.less)
    Module build failed:

    /* stylelint-disable declaration-bang-space-before */
    ^
    Cannot read property 'length' of undefined
          in C:\Users\JackMa\Desktop\demo\react_home\node_modules\antd\es\style\color\bezierEasing.less (line 1, column -1)
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--6-1!node_modules/less-loader/dist/cjs.js??ref--6-2!node_modules/antd/es/notification/style/index.less:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/notification/style/index.less] ./node_modules/css-loader??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/notification/style/index.less 287 bytes {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./node_modules/antd/es/notification/style/index.less (./node_modules/css-loader??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/notification/style/index.less)
    Module build failed:

    /* stylelint-disable declaration-bang-space-before */
    ^
    Cannot read property 'length' of undefined
          in C:\Users\JackMa\Desktop\demo\react_home\node_modules\antd\es\style\color\bezierEasing.less (line 1, column -1)
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--6-1!node_modules/less-loader/dist/cjs.js??ref--6-2!node_modules/antd/es/style/index.less:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/style/index.less] ./node_modules/css-loader??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/style/index.less 287 bytes {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./node_modules/antd/es/style/index.less (./node_modules/css-loader??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./node_modules/antd/es/style/index.less)
    Module build failed:

    /* stylelint-disable declaration-bang-space-before */
    ^
    Cannot read property 'length' of undefined
          in C:\Users\JackMa\Desktop\demo\react_home\node_modules\antd\es\style\color\bezierEasing.less (line 1, column -1)

**Comment by aiyuekuang** [comment]
你模块都安装了吗

**Comment by mawei1191546352** [comment]
安装了，是另外一个问题导致得这个。

**Comment by mawei1191546352** [comment]
安装了，是另外一个问题导致得这个。
