### ISSUE TITLE
部署上线白屏

### ISSUE THREAD

**Issue by Wing-Luo** [aiyuekuang/react_home#6]
为什么我部署到tomcat8.0的时候,先是首屏加载,然后加载完了之后就白屏了,我看console也没有报错,这是什么原因啊?

**Comment by aiyuekuang** [comment]
打包上线

将webpack.config.js中的publicPath的 http://111.111.11.11/build/ 改成你线上的地址，比如 http://129.0.0.111 之类，然后再执行npm run build
打包后直接将build文件夹提交至你们项目得根目录中
命令并且呵斥你们得后端人员，将404指向build/index.html，这样基本就可以愉快得查看了
如果在上线后首屏调用速度较慢，这样得情况得话，可以鞭挞后端人员，开启服务器得gzip压缩功能将js压缩一下，压缩后大小基本只有原来得三分之一，这个很实用



你应该是资源路径没有配置正确，你按照上面的再检查一遍

**Comment by Wing-Luo** [comment]
谢谢回复,我看看
